AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/**/*"
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
  Max: 100

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
