swagger: '2.0'
info:
  description: description
  version: 1.0.0
  title: Swagger Petstore
host: petstore.swagger.io
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: user
  - name: book
schemes:
  - http
paths:
  $ref: './paths/index.yml'
definitions:
  $ref: ./definitions/index.yml



  
