swagger: "2.0"
info:
  description: "description"
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/api/v1"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "user"
schemes:
- "http"
paths:
  /users:
    get:
      tags:
      - "user"
      summary: "全てのUserを取得"
      description: ""
      operationId: "getUsers"
      produces:
      - "appication/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
  /users/{userId}:
    get:
      tags:
      - "user"
      summary: "指定したUserを取得"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
      age:
        type: "integer"
      created_at: 
        type: "string"
      updated_at:
        type: "string"
    additionalProperties: false